Card component
Ash-D23/Stylish-Book-UI-Component-Library pull request #3
Opened 2022-01-30 10:53 UTC by Ash-D23

Please Review my Card Component

2022-01-30 14:50 UTC, samflab requested changes
Change the color of the strikethrough price (original price), make it grayish so that customer's focus goes on the discounted price

2022-01-30 15:16 UTC, Ash-D23 commented
@samflab thank you, have updated color for line-through

2022-01-30 20:55 UTC, NtshVrm approved these changes

2022-01-31 07:26 UTC, samflab approved these changes

2022-01-31 07:58 UTC, merged